language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdg-kolachi-website
  token:
    secure: SCooKM9HPhwOx+87CzvYOsryTqZi5m+rMlVPZkAQXZTVlmY+0xEVbxeZANyxm2hr38Ra+ACS9mz+oGZIZWIQfqDBJPYhRccxUpA1Aj8ANqrfYtX0IHYFZJLAWlkTQ9qClrm8O9vV2HL6j9tKJfVoFEM/ItimqPFKaZb6fCvaP3d3TQoACMwJ4GFlHUD4GxAENAmDHczNUnWAzTbmyVLhPM1o/8+VOHiPnrh+tUsqzgXp+rVNG23YF51v1R0CKl1yRhhpzc6QhgM7mWAAbxEVnyDz7ufxl5MAN1bZaNAlc9K1iU5mjH/fLV+RGpUsVL+X6r/KAoZaOeWESJ10q+VDg82/rs6DC5jgaKEECaOMSJas/GoDFyMzFvOs1bf4/aNfTDQfRoZjSIgnYRZ55A3qEhl2S7KFCCzL3CXouTGyTpyK9Ll938dB6Y1VpNA0HZwSLSZtDvww69URMY+RPXVNZvcXV6X/QVX+cl4yTo4AeSEcUlzkN0EjZg7aWSAXgcnKUIm0XFVnsKsmvIKWQxIPGOdwEnXBfjiQqXlsQPvo2j/KhzernRaCkQCrYfERxUo56ShtJyozVfcNGeXAtzn52MoPOY7KlpVQNcq4L++/R16NcerbR50E2LpzJrkSQFUanDwbwxcEU/uaYzAqiVyPeowWWnO4+hPmr3cOnovsVAU=
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: gdg-kolachi-website
  token:
    secure: SCooKM9HPhwOx+87CzvYOsryTqZi5m+rMlVPZkAQXZTVlmY+0xEVbxeZANyxm2hr38Ra+ACS9mz+oGZIZWIQfqDBJPYhRccxUpA1Aj8ANqrfYtX0IHYFZJLAWlkTQ9qClrm8O9vV2HL6j9tKJfVoFEM/ItimqPFKaZb6fCvaP3d3TQoACMwJ4GFlHUD4GxAENAmDHczNUnWAzTbmyVLhPM1o/8+VOHiPnrh+tUsqzgXp+rVNG23YF51v1R0CKl1yRhhpzc6QhgM7mWAAbxEVnyDz7ufxl5MAN1bZaNAlc9K1iU5mjH/fLV+RGpUsVL+X6r/KAoZaOeWESJ10q+VDg82/rs6DC5jgaKEECaOMSJas/GoDFyMzFvOs1bf4/aNfTDQfRoZjSIgnYRZ55A3qEhl2S7KFCCzL3CXouTGyTpyK9Ll938dB6Y1VpNA0HZwSLSZtDvww69URMY+RPXVNZvcXV6X/QVX+cl4yTo4AeSEcUlzkN0EjZg7aWSAXgcnKUIm0XFVnsKsmvIKWQxIPGOdwEnXBfjiQqXlsQPvo2j/KhzernRaCkQCrYfERxUo56ShtJyozVfcNGeXAtzn52MoPOY7KlpVQNcq4L++/R16NcerbR50E2LpzJrkSQFUanDwbwxcEU/uaYzAqiVyPeowWWnO4+hPmr3cOnovsVAU=
- provider: firebase
  skip_cleanup: true
  on:
    branch: hoverboard-v2
  project: gdg-kolachi-website
  token:
    secure: SCooKM9HPhwOx+87CzvYOsryTqZi5m+rMlVPZkAQXZTVlmY+0xEVbxeZANyxm2hr38Ra+ACS9mz+oGZIZWIQfqDBJPYhRccxUpA1Aj8ANqrfYtX0IHYFZJLAWlkTQ9qClrm8O9vV2HL6j9tKJfVoFEM/ItimqPFKaZb6fCvaP3d3TQoACMwJ4GFlHUD4GxAENAmDHczNUnWAzTbmyVLhPM1o/8+VOHiPnrh+tUsqzgXp+rVNG23YF51v1R0CKl1yRhhpzc6QhgM7mWAAbxEVnyDz7ufxl5MAN1bZaNAlc9K1iU5mjH/fLV+RGpUsVL+X6r/KAoZaOeWESJ10q+VDg82/rs6DC5jgaKEECaOMSJas/GoDFyMzFvOs1bf4/aNfTDQfRoZjSIgnYRZ55A3qEhl2S7KFCCzL3CXouTGyTpyK9Ll938dB6Y1VpNA0HZwSLSZtDvww69URMY+RPXVNZvcXV6X/QVX+cl4yTo4AeSEcUlzkN0EjZg7aWSAXgcnKUIm0XFVnsKsmvIKWQxIPGOdwEnXBfjiQqXlsQPvo2j/KhzernRaCkQCrYfERxUo56ShtJyozVfcNGeXAtzn52MoPOY7KlpVQNcq4L++/R16NcerbR50E2LpzJrkSQFUanDwbwxcEU/uaYzAqiVyPeowWWnO4+hPmr3cOnovsVAU=

